repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2
    hooks:
      - id: golangci-lint
        name: golangci-lint
        stages: [pre-commit]
        entry: golangci-lint run --new-from-rev=HEAD --fix
        types: [go]
        language: golang
        require_serial: true
        pass_filenames: false

      - id: golangci-lint-full
        name: golangci-lint-full
        stages: [pre-push]
        entry: golangci-lint run --fix
        types: [go]
        language: golang
        require_serial: true
        pass_filenames: false
  - repo: local
    hooks:
      - id: go-test-hook
        name: Go Test
        stages: [pre-push]
        entry: ./internal/hooks/test.sh
        language: script
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.11.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
